### ISSUE TITLE
Add licence files for both this project and the vendored replicate

### ISSUE THREAD

**Issue by tomviner** [simonw/llm-replicate#10]
Firstly for people to fork this plugin, you should add a licence. No doubt you intended one, but didn't remember yet.

Secondly, for the vendored replicate code, you should probably follow the the [pip Vendoring Policy](https://pip.pypa.io/en/stable/development/vendoring-policy/#vendoring-policy) rule:
> Vendored libraries MUST be accompanied with LICENSE files.

e.g. pip just puts the licence file along with the copied python files. See [examples here](https://github.com/pypa/pip/tree/main/src/pip/_vendor)

replicate [uses the Apache License 2.0](https://github.com/replicate/replicate-python/blob/main/LICENSE) which requires:
- License and copyright notice
- State changes

**Comment by simonw** [comment]
Good catch! Yes that was a mistake on my part (and I honestly forgot to do that for vendored code, I won't make that mistake in the future).

The good news is they shipped my fix so I can un-vendor that library now!

- https://github.com/replicate/replicate-python/pull/121

**Comment by simonw** [comment]
Added that Apache license file. I already had that marked in metadata here:

https://github.com/simonw/llm-replicate/blob/d1e6abe3c9aee2f29701687209427b9d42c2bd0f/pyproject.toml#L7
